---
  - hosts: localhost
    become: true
    become_user: root
    tasks:
      - name: Get DEB architecture
        shell: dpkg --print-architecture
        register: deb_architecture
      - name: add hashicorp repo
        apt_repository:
          repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/hashicorp.asc]  https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
          state: present
      - name: install packages
        package:
          name:
            - zsh
            - ca-certificates
            - curl
            - gnupg
            - python3-pip
            - python3-virtualenv
            - terraform
          state: present
      - name: install python packages
        pip:
          name:
            - pre-commit
          state: present
      - name: configure git identity
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.gitconfig"
          section: user
          option: email
          value: "{{ user_email }}"
      - name: configure git identity
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.gitconfig"
          section: user
          option: name
          value: "{{ user_fullname }}"
      - name: configure GCM
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.gitconfig"
          section: credential
          option: helper
          value: "{{ gcm_path }}"
      - name: configure awscli
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.aws/config"
          section: default
          option: region
          value: ap-southeast-2
      - name: zprofile
        vars:
          ansible_become: false
        file:
          path: "{{ home_dir }}/.zprofile"
          state: touch
      - name: configure zsh path
        vars:
          ansible_become: false
        lineinfile:
          dest: "{{ home_dir }}/.zprofile"
          regexp: '^export PATH.*'
          line: "export PATH=$PATH:~/bin/:/opt/aws/bin"
  - hosts: localhost
    become: true
    become_user: root
    roles:
     - role: gantsign.oh-my-zsh
       oh_my_zsh_theme:
       users:
        - username: "{{ local_user }}"
     - role: deekayen.awscli2
     - role: geerlingguy.docker
       docker_edition: ce
       docker_users:
        - "{{ local_user }}"
    tasks:
      - name: set p10k theme
        lineinfile:
          dest: "{{ home_dir }}/.zshrc"
          regexp: "^ZSH_THEME=.*"
          line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
      - name: configure p10k
        vars:
          ansible_become: false
        copy:
          src: files/.p10k.zsh
          dest: "{{ home_dir }}/.p10k.zsh"
      - name: set p10k theme
        lineinfile:
          dest: "{{ home_dir }}/.zshrc"
          line: "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"
