---
  - hosts: localhost
    become: true
    become_user: root
    tasks:
      - name: install packages
        package:
          name:
            - zsh
            - ca-certificates
            - curl
            - gnupg
            - python3-pip
            - python3-virtualenv
          state: present
      - name: configure git identity
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.gitconfig"
          section: user
          option: email
          value: "{{ user_email }}"
      - name: configure git identity
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.gitconfig"
          section: user
          option: name
          value: "{{ user_fullname }}"
      - name: configure GCM
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.gitconfig"
          section: credential
          option: helper
          value: "{{ gcm_path }}"
      - name: configure awscli
        vars:
          ansible_become: false
        ini_file:
          path: "{{ home_dir }}/.aws/config"
          section: default
          option: region
          value: ap-southeast-2
      - name: zprofile
        vars:
          ansible_become: false
        file:
          path: "{{ home_dir }}/.zprofile"
          state: touch
      - name: configure zsh path
        vars:
          ansible_become: false
        lineinfile:
          dest: "{{ home_dir }}/.zprofile"
          regexp: '^export PATH.*'
          line: "export PATH=$PATH:~/bin/:/opt/aws/bin"
  - hosts: localhost
    become: true
    become_user: root
    roles:
     - role: deekayen.awscli2
     - role: geerlingguy.docker
       docker_edition: ce
       docker_users:
        - "{{ local_user }}"