all:
  vars:
    local_user: "luke"
    home_dir: "/home/luke"
    user_email: "luke.dudney@fortescue.com"
    user_fullname: "Luke Dudney"
    gcm_path: "/mnt/c/Users/ldudney/AppData/Local/Programs/Git/mingw64/bin/git-credential-manager.exe"